#!/usr/bin/env bash
# Install and configure HAproxy on Load Balancer server

sudo  apt-get -y update
sudo apt-get -y install haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend amilemia.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 386741-web-01 52.3.244.240:80 check
    server 386741-web-02 52.91.146.187:80 check
EOF

haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
