#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line.
var=0
while [ $var -le 9 ]
do
	if [ "$var" -eq 9 ]
	then
		echo $"Hi"
	fi
	echo $"Best School"
	((var++))
done
