#!/usr/bin/env bash
# script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

var=1
while [ $var -le 20 ]; do
	case $var in
	4)
	       	echo $var; echo $"bad luck from China"
		;;
	9)
	       	echo $var; echo $"bad luck from Japan"
		;;
	17)
		echo $var; echo $"bad luck from Italy"
		;;
	*)
		echo $var
esac
	((var++))
done
