#!/usr/bin/env bash
# Generate the RSA key pair with the specified key size and passphrase

# Set the desired key file name and passphrase
key_name="school"
passphrase="betty"

# Generate the RSA key pair with the specified key size and passphrase
ssh-keygen -t rsa -b 4096 -f $key_name -N $passphrase
